In [1]:
import numpy as np

In [33]:
def euclidian(arr1, arr2):
    if (arr1.shape[1] != arr2.shape[1]):
        return None
    
    res_arr = np.empty((arr2.shape[0], arr1.shape[0]))
    for enum, item in enumerate(arr2[:,]):
        res_arr[enum] = np.sqrt(np.sum((arr1 - item) ** 2, axis=1))
    
    return res_arr

def cos_metrics(arr1, arr2):
    if (arr1.shape[1] != arr2.shape[1]):
        return None
    
    res_arr = np.empty((arr2.shape[0], arr1.shape[0]))
    for enum, item in enumerate(arr2[:,]):
        res_arr[enum] = np.sum(arr1 * item, axis=1) / (
            (np.sqrt(np.sum(arr1 * arr1, axis=1)) * 
             np.sqrt((np.sum(item * item)))))
        
    return res_arr

In [123]:
def euclidean_distance(x, y):
    return np.sqrt(((x - y.T).T ** 2).sum(axis=0))
def cosine_distance(x, y):
    return np.dot(x, y.T).T / np.sqrt((x ** 2).sum(axis = 1)) / np.sqrt((y ** 2).sum(axis = 1))[:,None]

In [5]:
x = np.array([[4, 6, 2], [5, 3, 8], [7, 5, 2]])
y = np.array([[3, 4, 5], [7, 2, 1]])

In [9]:
x[...,np.newaxis].sum(axis=2)

array([[4, 6, 2],
       [5, 3, 8],
       [7, 5, 2]])

In [26]:
np.sqrt(((x[...,np.newaxis] - y[...,np.newaxis].T).T ** 2).sum(axis = 1))

array([[3.74165739, 3.74165739, 5.09901951],
       [5.09901951, 7.34846923, 3.16227766]])

In [40]:
(x[...,np.newaxis] * y[...,np.newaxis].T).T / np.sqrt(np.sum(np.square(x), axis=0))

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,) 

In [110]:
euclidean_distance(x, y)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [88]:
euclidian(x, y)

array([[3.74165739, 3.74165739, 5.09901951],
       [5.09901951, 7.34846923, 3.16227766]])

In [89]:
np.linalg.norm(y, axis = 1)

array([7.07106781, 7.34846923])

In [97]:
np.sqrt((y ** 2).sum(axis = 1))[:,None]

array([[7.07106781],
       [7.34846923]])

In [98]:
np.sqrt((x ** 2).sum(axis = 1))[None, :]

array([[7.48331477, 9.89949494, 8.83176087]])

In [102]:
np.sqrt(((x[..., np.newaxis] - y[...,np.newaxis].T).T ** 2).sum(axis=1))

array([[3.74165739, 3.74165739, 5.09901951],
       [5.09901951, 7.34846923, 3.16227766]])

In [111]:
np.dot(x, y.T).T / np.sqrt((x ** 2).sum(axis = 1))[None, :] / np.sqrt((y ** 2).sum(axis = 1))[:,None]

array([[0.86931829, 0.95714286, 0.81665358],
       [0.76376262, 0.67357531, 0.93990867]])

In [122]:
np.sqrt((x ** 2).sum(axis=1))

array([7.48331477, 9.89949494, 8.83176087])

In [158]:
x ** 2

array([[16, 36,  4],
       [25,  9, 64],
       [49, 25,  4]])

In [166]:
np.sqrt(((x[:,np.newaxis] - y) ** 2).sum(axis=2).T)

array([[3.74165739, 3.74165739, 5.09901951],
       [5.09901951, 7.34846923, 3.16227766]])

In [150]:
np.sqrt(((x[..., None] - y[..., None].T).T ** 2).sum(axis=1))

array([[3.74165739, 3.74165739, 5.09901951],
       [5.09901951, 7.34846923, 3.16227766]])