In [1]:
import numpy as np
from sklearn.datasets import fetch_mldata

In [2]:
mnist = fetch_mldata("MNIST-original")
data = mnist.data / 255.0
target = mnist.target.astype("int0")

/usr/local/lib/python3.7/site-packages/sklearn/utils/deprecation.py:85: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22. Please use fetch_openml.
  warnings.warn(msg, category=DeprecationWarning)
/usr/local/lib/python3.7/site-packages/sklearn/utils/deprecation.py:85: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22. Please use fetch_openml.
  warnings.warn(msg, category=DeprecationWarning)


In [3]:
train_data = data[:100]
test_data = target[:100]
train_data.shape

(100, 784)

In [9]:
def euclidean_distance(x, y):
    return np.sqrt(((x[:, np.newaxis] - y) ** 2).sum(axis=2).T)

def second(x, y):
    return np.sqrt(np.sum(x ** 2, axis=1)[:,np.newaxis] + np.sum(y ** 2, axis=1)
            - 2 * np.dot(x, np.transpose(y))).T

In [10]:
from nearest_neighbors import KNNClassifier

In [18]:
for item in euclidean_distance(train_data[:20], train_data[:10]):
    print(item)
    print(np.argsort(item))

[ 0.          5.44315986  9.17770898  7.20919892  8.13929103  9.35950442
  8.59347857 11.26246586  9.48979905  7.69946847  7.51389434  9.25145582
  7.32727652 11.0850565   8.54222432  6.92695563  5.67865886 10.88540922
  8.57069029  8.47465135]
[ 0  1 16 15  3 12 10  9  4 19 14 18  6  2 11  5  8 17 13  7]
[ 5.44315986  0.          9.88612751  8.36712319  7.71483689  9.75418364
  8.21448913 11.71969888  9.88435087  7.96010236  8.48936825  9.96389715
  8.69539733 11.61670899  7.93163988  8.10432363  5.11626305 11.06932126
  8.4639898   9.42695261]
[ 1 16  0  4 14  9 15  6  3 18 10 12 19  5  8  2 11 17 13  7]
[ 9.17770898  9.88612751  0.          5.84768477 11.28997064 11.67657645
 10.05671116 12.36572075  7.37517684  7.52925858  6.26066487 11.76789173
  7.63955388 12.11757282 11.80719126  9.86444846  9.81152333 13.31118634
 11.72108777  6.80086726]
[ 2  3 10 19  8  9 12  0 16 15  1  6  4  5 18 11 14 13  7 17]
[ 7.20919892  8.36712319  5.84768477  0.         10.66559034 10.73297298
  9.24

In [19]:
for item in second(train_data[:20], train_data[:10]):
    print(item)
    print(np.argsort(item))

[        nan  5.44315986  9.17770898  7.20919892  8.13929103  9.35950442
  8.59347857 11.26246586  9.48979905  7.69946847  7.51389434  9.25145582
  7.32727652 11.0850565   8.54222432  6.92695563  5.67865886 10.88540922
  8.57069029  8.47465135]
[ 1 16 15  3 12 10  9  4 19 14 18  6  2 11  5  8 17 13  7  0]
[5.44315986e+00 2.38418579e-07 9.88612751e+00 8.36712319e+00
 7.71483689e+00 9.75418364e+00 8.21448913e+00 1.17196989e+01
 9.88435087e+00 7.96010236e+00 8.48936825e+00 9.96389715e+00
 8.69539733e+00 1.16167090e+01 7.93163988e+00 8.10432363e+00
 5.11626305e+00 1.10693213e+01 8.46398980e+00 9.42695261e+00]
[ 1 16  0  4 14  9 15  6  3 18 10 12 19  5  8  2 11 17 13  7]
[9.17770898e+00 9.88612751e+00 2.92001932e-07 5.84768477e+00
 1.12899706e+01 1.16765764e+01 1.00567112e+01 1.23657207e+01
 7.37517684e+00 7.52925858e+00 6.26066487e+00 1.17678917e+01
 7.63955388e+00 1.21175728e+01 1.18071913e+01 9.86444846e+00
 9.81152333e+00 1.33111863e+01 1.17210878e+01 6.80086726e+00]
[ 2  3 10 19  8  9 

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  


In [20]:
euclidean_distance(train_data[:20], train_data[:10]) - second(train_data[:20], train_data[:10])

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  


array([[            nan,  4.44089210e-15,  1.77635684e-15,
        -2.66453526e-15,  1.77635684e-15,  1.77635684e-15,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.77635684e-15,  0.00000000e+00,  1.77635684e-15,
         8.88178420e-16,  0.00000000e+00, -1.77635684e-15,
        -1.77635684e-15,  7.10542736e-15,  0.00000000e+00,
         0.00000000e+00, -1.77635684e-15],
       [ 4.44089210e-15, -2.38418579e-07,  0.00000000e+00,
         1.77635684e-15, -1.77635684e-15,  1.77635684e-15,
        -5.32907052e-15,  1.77635684e-15,  1.77635684e-15,
        -8.88178420e-16,  1.77635684e-15,  0.00000000e+00,
         0.00000000e+00,  1.77635684e-15,  8.88178420e-16,
         1.77635684e-15, -8.88178420e-16, -1.77635684e-15,
         0.00000000e+00, -1.77635684e-15],
       [ 1.77635684e-15,  0.00000000e+00, -2.92001932e-07,
        -4.44089210e-15,  0.00000000e+00, -3.55271368e-15,
         0.00000000e+00,  0.00000000e+00,  1.77635684e-15,
        -1.77635684e-15, -2.6