In [1]:
import numpy as np

In [2]:
array_target = np.array([[2, 2, 3, 4, 5], [0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
array_target

array([[2, 2, 3, 4, 5],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
array_left = np.array([[0, 1, 0], [0, 0, 1], [0, 0, 0]])
array_left

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [46]:
array = np.dot(array_left, array_target)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 0, 0, 0, 0]])

In [24]:
array_right = np.array([[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0]])
array_right

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [27]:
np.dot(array, array_right)

array([[2, 3, 4, 0, 0],
       [7, 8, 9, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
array_hard = np.arange(100).reshape(-1, 2, 5)
array_hard.shape

(10, 2, 5)

In [21]:
array_dot = np.array([[0, 1], [1, 0]])
array_dot = np.concatenate([array_dot, array_dot])
array_dot

array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 0]])

array([[[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]],

       [[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]])

In [36]:
eye_matrix = np.zeros((28, 28)).astype(int)

In [44]:
for enum_1, item_1 in enumerate(eye_matrix):
    if enum_1 -1 >= 0:
        item_1[enum_1 - 1] = 1

In [45]:
for item in eye_matrix:
    print(item)

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0