In [1]:
import numpy as np

In [55]:
X = (np.random.rand(10)).reshape(2, 5)

In [56]:
X

array([[0.62561531, 0.39213037, 0.58723585, 0.44099109, 0.49215975],
       [0.73903522, 0.14666558, 0.50546916, 0.42356795, 0.38791532]])

In [57]:
w = (np.random.rand(5))
w

array([0.89879598, 0.37701785, 0.39746623, 0.16392458, 0.17610776])

In [58]:
# w^T * w
np.sum(w ** 2)

1.165841296212393

In [59]:
y = np.array([1, -1])
y

array([ 1, -1])

In [60]:
def Mi(y, w, x):
    return y * np.sum(w * x)

In [61]:
M = []
for i in range(y.__len__()):
    M.append(Mi(y[i], w, X[i]))
    
M = np.array(M)
M

array([ 1.10250952, -1.05819245])

In [115]:
(w * X * y[:, None]).sum(axis = 1)

array([ 1.10250952, -1.05819245])

In [135]:
X.dot(w) * y

array([ 1.10250952, -1.05819245])

In [62]:
L = np.log(1 + np.exp(-1 * M))
L

array([0.28670919, 1.35613368])

In [64]:
lamb = 3

In [65]:
Q = 1 / y.__len__() * np.sum(L) + lamb / 2 * np.sum(w ** 2)

In [66]:
Q

2.5701833761561246

In [77]:
#grad from Q

In [67]:
M

array([ 1.10250952, -1.05819245])

In [159]:
sub_sum = np.exp(-1 * M) / (1 + np.exp(-1 * M)) * (-1) * y / y.__len__()
sub_sum

array([-0.12463499,  0.37117248])

In [160]:
vector_sub = sub_sum[:, None] * X
vector_sub

array([[-0.07797356, -0.04887316, -0.07319013, -0.05496292, -0.06134033],
       [ 0.27430954,  0.05443823,  0.18761624,  0.15721677,  0.14398349]])

In [163]:
attempt.T.dot(sub_sum)

array([0.19633598, 0.00556506, 0.11442611, 0.10225385, 0.08264317])

In [161]:
first_part = vector_sub.sum(axis = 0)
first_part

array([0.19633598, 0.00556506, 0.11442611, 0.10225385, 0.08264317])

ValueError: shapes (2,5) and (2,1) not aligned: 5 (dim 1) != 2 (dim 0)

In [95]:
second_part = lamb * w
second_part

array([2.69638795, 1.13105354, 1.19239869, 0.49177374, 0.52832328])

In [96]:
first_part + second_part

array([2.89272394, 1.1366186 , 1.3068248 , 0.59402759, 0.61096645])

In [106]:

class BaseSmoothOracle:
    """
    Базовый класс для реализации оракулов.
    """
    def func(self, w):
        """
        Вычислить значение функции в точке w.
        """
        raise NotImplementedError('Func oracle is not implemented.')

    def grad(self, w):
        """
        Вычислить значение градиента функции в точке w.
        """
        raise NotImplementedError('Grad oracle is not implemented.')

        
class BinaryLogistic(BaseSmoothOracle):
    """
    Оракул для задачи двухклассовой логистической регрессии.
    
    Оракул должен поддерживать l2 регуляризацию.
    """
    
    def __init__(self, l2_coef):
        """
        Задание параметров оракула.
        
        l2_coef - коэффициент l2 регуляризации
        """
        self.l2 = l2_coef
     
    def func(self, X, y, w):
        """
        Вычислить значение функционала в точке w на выборке X с ответами y.
        
        X - scipy.sparse.csr_matrix или двумерный numpy.array
        
        y - одномерный numpy array
        
        w - одномерный numpy array
        """
        return super().func(w)
        
    def grad(self, X, y, w):
        """
        Вычислить градиент функционала в точке w на выборке X с ответами y.
        
        X - scipy.sparse.csr_matrix или двумерный numpy.array
        
        y - одномерный numpy array
        
        w - одномерный numpy array
        """
        return super().grad(w)
    

In [107]:
log = BinaryLogistic(0)

In [108]:
log.func(X, y, w)

[[0.62561531 0.39213037 0.58723585 0.44099109 0.49215975]
 [0.73903522 0.14666558 0.50546916 0.42356795 0.38791532]]


In [120]:
import scipy.sparse as sp

In [122]:
attempt = sp.csr_matrix(X)

TypeError: loop of ufunc does not support argument 0 of type csr_matrix which has no callable log method

In [139]:
attempt

<2x5 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>